### ISSUE TITLE
Button to clear all items at once

### ISSUE THREAD

**Issue by kevinkendzia** [xdev-software/vaadin-chip-combobox#16]
It would be nice to have the possibility to clear all selected items at once.

Maybe the clear button of the internal combobox could be used? The ChipCombobox could be listening to the valueChange-Event of the internal combobox and react to an selected null-value (vaadin default to reset a component)

Otherwise an separate clear button would be nice.

**Comment by AB-xdev** [comment]
I think we should first collect some implementation ideas:

Maybe use a Trash icon when >=1 chip is "selected"/shown:
![grafik](https://user-images.githubusercontent.com/45384811/124727498-108b4c00-df0f-11eb-9f84-a75dcd3488a6.png)

**Comment by MSa-xdev** [comment]
I have collected some ideas where to place the trash icon. 
1. Next to the ComboBox
![grafik](https://user-images.githubusercontent.com/86833123/126175518-2baa9c6d-d287-486b-9554-9e825a235b94.png)

2. Next to the chips. The problem here is that when the chips wrap, the last chip has a larger distance to the trash icon. This needs to be fixed separately.
![grafik](https://user-images.githubusercontent.com/86833123/126175357-1c4ceb49-a82b-4175-958f-9cb88a034152.png)

![grafik](https://user-images.githubusercontent.com/86833123/126175314-964a710c-a1ca-40db-b81b-bd0e683ccd30.png)

3. Directly behind the last chip.
![grafik](https://user-images.githubusercontent.com/86833123/126175756-b82b28ca-ca7e-49f9-ad18-d24aa3cbf791.png)

**Comment by AB-xdev** [comment]
In my opinion the first option would be the best one:
* The trash can is fixed -> No movement, user can click always the same spot
* No problems with breaking components, etc

I think we should implement that.

**Comment by kevinkendzia** [comment]
I think option 1 is the best choice, too. 
But please ensure that the combobox can be stretched to full size, so combobox + trash are as long as the chip container.
And would it be possible to make the icon switchable?

**Comment by MSa-xdev** [comment]
I will implement the above mentioned features.
